// Instrument Preset Library
// Provides a collection of synthesizer presets organized by category

export interface InstrumentPreset {
  name: string;
  category: string;
  settings: {
    // Oscillator 1
    osc1Type: "sine" | "square" | "sawtooth" | "triangle";
    osc1Octave: number;
    osc1Semitone: number;
    osc1Detune: number;
    osc1Shape: number;

    // Oscillator 2
    osc2Type: "sine" | "square" | "sawtooth" | "triangle";
    osc2Octave: number;
    osc2Semitone: number;
    osc2Detune: number;
    osc2Shape: number;

    // Oscillator Mix
    oscMix: number;
    ringMod: number;

    // Amp Envelope
    attack: number;
    decay: number;
    sustain: number;
    release: number;

    // Amp
    volume: number;
    drive: number;

    // Filter
    filterType: "lowpass" | "highpass" | "bandpass" | "notch";
    filterFreq: number;
    filterQ: number;
    filterEnvAmount: number;
    filterKeyTrack: number;

    // Filter Envelope
    filterAttack: number;
    filterDecay: number;
    filterSustain: number;
    filterRelease: number;
    filterBaseFreq: number;
    filterOctaves: number;

    // Portamento
    portamento: number;
    portamentoMode: "always" | "legato" | "off";

    // LFO
    lfoRate: number;
    lfoDepth: number;
    lfoType: "sine" | "square" | "sawtooth" | "triangle";
    lfoOsc1Amount: number;
    lfoOsc2Amount: number;
    lfoFilterAmount: number;
    lfoAmpAmount: number;

    // Delay
    delayTime: number;
    delayFeedback: number;
    delayWet: number;

    // Reverb
    reverbDecay: number;
    reverbWet: number;
    reverbSize: number;
    reverbStereo: number;
    reverbDamping: number;
  };
}

// Comprehensive preset library organized by instrument families
export const INSTRUMENT_PRESETS: InstrumentPreset[] = [
  // ========== PIANO FAMILY ==========
  {
    name: "Acoustic Grand Piano",
    category: "piano",
    settings: {
      osc1Type: "triangle",
      osc1Octave: 0,
      osc1Semitone: 0,
      osc1Detune: 0,
      osc1Shape: 0,
      osc2Type: "sine",
      osc2Octave: 1,
      osc2Semitone: 0,
      osc2Detune: -5,
      osc2Shape: 0,
      oscMix: 0.2,
      ringMod: 0,
      attack: 0.002,
      decay: 0.3,
      sustain: 0.2,
      release: 0.8,
      volume: -4,
      drive: 0,
      filterType: "lowpass",
      filterFreq: 3500,
      filterQ: 0.8,
      filterEnvAmount: 0.3,
      filterKeyTrack: 0.5,
      filterAttack: 0.001,
      filterDecay: 0.2,
      filterSustain: 0.3,
      filterRelease: 0.5,
      filterBaseFreq: 800,
      filterOctaves: 4,
      portamento: 0,
      portamentoMode: "off",
      lfoRate: 0,
      lfoDepth: 0,
      lfoType: "sine",
      lfoOsc1Amount: 0,
      lfoOsc2Amount: 0,
      lfoFilterAmount: 0,
      lfoAmpAmount: 0,
      delayTime: 0,
      delayFeedback: 0,
      delayWet: 0,
      reverbDecay: 2.0,
      reverbWet: 0.25,
      reverbSize: 0.7,
      reverbStereo: 0.6,
      reverbDamping: 0.4,
    },
  },

  {
    name: "Electric Piano",
    category: "piano",
    settings: {
      osc1Type: "triangle",
      osc1Octave: 0,
      osc1Semitone: 0,
      osc1Detune: 0,
      osc1Shape: 0.3,
      osc2Type: "sine",
      osc2Octave: 0,
      osc2Semitone: 7,
      osc2Detune: 2,
      osc2Shape: 0,
      oscMix: 0.5,
      ringMod: 0.1,
      attack: 0.003,
      decay: 0.2,
      sustain: 0.4,
      release: 0.5,
      volume: -6,
      drive: 0.15,
      filterType: "lowpass",
      filterFreq: 2800,
      filterQ: 1.2,
      filterEnvAmount: 0.4,
      filterKeyTrack: 0.6,
      filterAttack: 0.005,
      filterDecay: 0.15,
      filterSustain: 0.3,
      filterRelease: 0.4,
      filterBaseFreq: 600,
      filterOctaves: 3,
      portamento: 0,
      portamentoMode: "off",
      lfoRate: 4.5,
      lfoDepth: 0.05,
      lfoType: "sine",
      lfoOsc1Amount: 0,
      lfoOsc2Amount: 0,
      lfoFilterAmount: 0,
      lfoAmpAmount: 0.05,
      delayTime: 0,
      delayFeedback: 0,
      delayWet: 0,
      reverbDecay: 1.5,
      reverbWet: 0.3,
      reverbSize: 0.5,
      reverbStereo: 0.6,
      reverbDamping: 0.4,
    },
  },

  // ========== BASS FAMILY ==========
  {
    name: "Acoustic Bass",
    category: "bass",
    settings: {
      osc1Type: "sine",
      osc1Octave: -1,
      osc1Semitone: 0,
      osc1Detune: 0,
      osc1Shape: 0,
      osc2Type: "sawtooth",
      osc2Octave: -1,
      osc2Semitone: -7,
      osc2Detune: -3,
      osc2Shape: 0,
      oscMix: 0.3,
      ringMod: 0,
      attack: 0.01,
      decay: 0.2,
      sustain: 0.7,
      release: 0.8,
      volume: -3,
      drive: 0.2,
      filterType: "lowpass",
      filterFreq: 300,
      filterQ: 1.5,
      filterEnvAmount: 0.2,
      filterKeyTrack: 0.3,
      filterAttack: 0.01,
      filterDecay: 0.15,
      filterSustain: 0.5,
      filterRelease: 0.3,
      filterBaseFreq: 200,
      filterOctaves: 2,
      portamento: 0.08,
      portamentoMode: "legato",
      lfoRate: 0,
      lfoDepth: 0,
      lfoType: "sine",
      lfoOsc1Amount: 0,
      lfoOsc2Amount: 0,
      lfoFilterAmount: 0,
      lfoAmpAmount: 0,
      delayTime: 0,
      delayFeedback: 0,
      delayWet: 0,
      reverbDecay: 1.0,
      reverbWet: 0.15,
      reverbSize: 0.5,
      reverbStereo: 0.3,
      reverbDamping: 0.5,
    },
  },

  {
    name: "Synth Bass",
    category: "bass",
    settings: {
      osc1Type: "sawtooth",
      osc1Octave: -1,
      osc1Semitone: 0,
      osc1Detune: 0,
      osc1Shape: 0,
      osc2Type: "square",
      osc2Octave: -2,
      osc2Semitone: 0,
      osc2Detune: 5,
      osc2Shape: 0.5,
      oscMix: 0.6,
      ringMod: 0,
      attack: 0.005,
      decay: 0.1,
      sustain: 0.8,
      release: 0.3,
      volume: -2,
      drive: 0.25,
      filterType: "lowpass",
      filterFreq: 400,
      filterQ: 3.0,
      filterEnvAmount: 0.6,
      filterKeyTrack: 0.4,
      filterAttack: 0.005,
      filterDecay: 0.1,
      filterSustain: 0.2,
      filterRelease: 0.2,
      filterBaseFreq: 150,
      filterOctaves: 3,
      portamento: 0.05,
      portamentoMode: "always",
      lfoRate: 0,
      lfoDepth: 0,
      lfoType: "sine",
      lfoOsc1Amount: 0,
      lfoOsc2Amount: 0,
      lfoFilterAmount: 0,
      lfoAmpAmount: 0,
      delayTime: 0,
      delayFeedback: 0,
      delayWet: 0,
      reverbDecay: 0.8,
      reverbWet: 0.1,
      reverbSize: 0.3,
      reverbStereo: 0.2,
      reverbDamping: 0.7,
    },
  },

  {
    name: "Sub Bass",
    category: "bass",
    settings: {
      osc1Type: "sine",
      osc1Octave: -2,
      osc1Semitone: 0,
      osc1Detune: 0,
      osc1Shape: 0,
      osc2Type: "sine",
      osc2Octave: -1,
      osc2Semitone: 0,
      osc2Detune: 0,
      osc2Shape: 0,
      oscMix: 0.4,
      ringMod: 0,
      attack: 0.01,
      decay: 0.15,
      sustain: 0.9,
      release: 0.4,
      volume: 0,
      drive: 0.3,
      filterType: "lowpass",
      filterFreq: 200,
      filterQ: 2.0,
      filterEnvAmount: 0.3,
      filterKeyTrack: 0.2,
      filterAttack: 0.01,
      filterDecay: 0.1,
      filterSustain: 0.4,
      filterRelease: 0.2,
      filterBaseFreq: 100,
      filterOctaves: 2,
      portamento: 0.1,
      portamentoMode: "always",
      lfoRate: 0,
      lfoDepth: 0,
      lfoType: "sine",
      lfoOsc1Amount: 0,
      lfoOsc2Amount: 0,
      lfoFilterAmount: 0,
      lfoAmpAmount: 0,
      delayTime: 0,
      delayFeedback: 0,
      delayWet: 0,
      reverbDecay: 0.5,
      reverbWet: 0.05,
      reverbSize: 0.2,
      reverbStereo: 0.1,
      reverbDamping: 0.8,
    },
  },

  // ========== LEAD FAMILY ==========
  {
    name: "Lead Square",
    category: "lead",
    settings: {
      osc1Type: "square",
      osc1Octave: 0,
      osc1Semitone: 0,
      osc1Detune: 0,
      osc1Shape: 0.6,
      osc2Type: "square",
      osc2Octave: 0,
      osc2Semitone: 0,
      osc2Detune: 8,
      osc2Shape: 0.4,
      oscMix: 0.5,
      ringMod: 0,
      attack: 0.01,
      decay: 0.3,
      sustain: 0.6,
      release: 0.4,
      volume: -8,
      drive: 0.3,
      filterType: "lowpass",
      filterFreq: 1500,
      filterQ: 2.5,
      filterEnvAmount: 0.8,
      filterKeyTrack: 0.7,
      filterAttack: 0.01,
      filterDecay: 0.2,
      filterSustain: 0.4,
      filterRelease: 0.3,
      filterBaseFreq: 500,
      filterOctaves: 5,
      portamento: 0.1,
      portamentoMode: "legato",
      lfoRate: 6,
      lfoDepth: 0.1,
      lfoType: "sine",
      lfoOsc1Amount: 0.1,
      lfoOsc2Amount: 0,
      lfoFilterAmount: 0.2,
      lfoAmpAmount: 0,
      delayTime: 0.25,
      delayFeedback: 0.3,
      delayWet: 0.2,
      reverbDecay: 1.5,
      reverbWet: 0.2,
      reverbSize: 0.5,
      reverbStereo: 0.5,
      reverbDamping: 0.5,
    },
  },

  {
    name: "Lead Saw",
    category: "lead",
    settings: {
      osc1Type: "sawtooth",
      osc1Octave: 0,
      osc1Semitone: 0,
      osc1Detune: -5,
      osc1Shape: 0,
      osc2Type: "sawtooth",
      osc2Octave: 0,
      osc2Semitone: 0,
      osc2Detune: 5,
      osc2Shape: 0,
      oscMix: 0.5,
      ringMod: 0,
      attack: 0.005,
      decay: 0.2,
      sustain: 0.7,
      release: 0.3,
      volume: -6,
      drive: 0.2,
      filterType: "lowpass",
      filterFreq: 2000,
      filterQ: 2.0,
      filterEnvAmount: 0.7,
      filterKeyTrack: 0.8,
      filterAttack: 0.005,
      filterDecay: 0.15,
      filterSustain: 0.5,
      filterRelease: 0.25,
      filterBaseFreq: 600,
      filterOctaves: 4,
      portamento: 0.08,
      portamentoMode: "legato",
      lfoRate: 5,
      lfoDepth: 0.08,
      lfoType: "triangle",
      lfoOsc1Amount: 0,
      lfoOsc2Amount: 0,
      lfoFilterAmount: 0.15,
      lfoAmpAmount: 0,
      delayTime: 0.375,
      delayFeedback: 0.25,
      delayWet: 0.15,
      reverbDecay: 1.2,
      reverbWet: 0.18,
      reverbSize: 0.4,
      reverbStereo: 0.4,
      reverbDamping: 0.5,
    },
  },

  {
    name: "Acid Lead",
    category: "lead",
    settings: {
      osc1Type: "sawtooth",
      osc1Octave: 0,
      osc1Semitone: 0,
      osc1Detune: 0,
      osc1Shape: 0,
      osc2Type: "square",
      osc2Octave: -1,
      osc2Semitone: 0,
      osc2Detune: 7,
      osc2Shape: 0.7,
      oscMix: 0.3,
      ringMod: 0,
      attack: 0.001,
      decay: 0.15,
      sustain: 0.5,
      release: 0.2,
      volume: -5,
      drive: 0.4,
      filterType: "lowpass",
      filterFreq: 800,
      filterQ: 5.0,
      filterEnvAmount: 1.0,
      filterKeyTrack: 0.9,
      filterAttack: 0.001,
      filterDecay: 0.1,
      filterSustain: 0.1,
      filterRelease: 0.15,
      filterBaseFreq: 300,
      filterOctaves: 6,
      portamento: 0.05,
      portamentoMode: "always",
      lfoRate: 0,
      lfoDepth: 0,
      lfoType: "sine",
      lfoOsc1Amount: 0,
      lfoOsc2Amount: 0,
      lfoFilterAmount: 0,
      lfoAmpAmount: 0,
      delayTime: 0,
      delayFeedback: 0,
      delayWet: 0,
      reverbDecay: 0.8,
      reverbWet: 0.1,
      reverbSize: 0.3,
      reverbStereo: 0.3,
      reverbDamping: 0.6,
    },
  },

  // ========== PAD FAMILY ==========
  {
    name: "Warm Pad",
    category: "pad",
    settings: {
      osc1Type: "sawtooth",
      osc1Octave: 0,
      osc1Semitone: 0,
      osc1Detune: -8,
      osc1Shape: 0,
      osc2Type: "sawtooth",
      osc2Octave: 0,
      osc2Semitone: 7,
      osc2Detune: 8,
      osc2Shape: 0,
      oscMix: 0.5,
      ringMod: 0,
      attack: 0.8,
      decay: 0.5,
      sustain: 0.8,
      release: 2.0,
      volume: -10,
      drive: 0.05,
      filterType: "lowpass",
      filterFreq: 1200,
      filterQ: 0.7,
      filterEnvAmount: 0.3,
      filterKeyTrack: 0.5,
      filterAttack: 0.5,
      filterDecay: 0.8,
      filterSustain: 0.6,
      filterRelease: 1.5,
      filterBaseFreq: 400,
      filterOctaves: 3,
      portamento: 0.3,
      portamentoMode: "always",
      lfoRate: 0.3,
      lfoDepth: 0.05,
      lfoType: "sine",
      lfoOsc1Amount: 0.02,
      lfoOsc2Amount: 0,
      lfoFilterAmount: 0.1,
      lfoAmpAmount: 0.08,
      delayTime: 0.5,
      delayFeedback: 0.4,
      delayWet: 0.25,
      reverbDecay: 3.5,
      reverbWet: 0.5,
      reverbSize: 0.9,
      reverbStereo: 0.8,
      reverbDamping: 0.3,
    },
  },

  {
    name: "String Pad",
    category: "pad",
    settings: {
      osc1Type: "sawtooth",
      osc1Octave: 0,
      osc1Semitone: 0,
      osc1Detune: -10,
      osc1Shape: 0,
      osc2Type: "sawtooth",
      osc2Octave: 0,
      osc2Semitone: 0,
      osc2Detune: 10,
      osc2Shape: 0,
      oscMix: 0.5,
      ringMod: 0,
      attack: 1.0,
      decay: 0.6,
      sustain: 0.9,
      release: 2.5,
      volume: -12,
      drive: 0,
      filterType: "lowpass",
      filterFreq: 1800,
      filterQ: 0.5,
      filterEnvAmount: 0.2,
      filterKeyTrack: 0.6,
      filterAttack: 0.8,
      filterDecay: 1.0,
      filterSustain: 0.7,
      filterRelease: 2.0,
      filterBaseFreq: 500,
      filterOctaves: 3,
      portamento: 0.4,
      portamentoMode: "always",
      lfoRate: 0.5,
      lfoDepth: 0.03,
      lfoType: "triangle",
      lfoOsc1Amount: 0.03,
      lfoOsc2Amount: 0,
      lfoFilterAmount: 0.05,
      lfoAmpAmount: 0.1,
      delayTime: 0,
      delayFeedback: 0,
      delayWet: 0,
      reverbDecay: 4.0,
      reverbWet: 0.6,
      reverbSize: 0.95,
      reverbStereo: 0.9,
      reverbDamping: 0.2,
    },
  },

  {
    name: "Choir Pad",
    category: "pad",
    settings: {
      osc1Type: "triangle",
      osc1Octave: 0,
      osc1Semitone: 0,
      osc1Detune: -7,
      osc1Shape: 0.2,
      osc2Type: "triangle",
      osc2Octave: 0,
      osc2Semitone: 5,
      osc2Detune: 7,
      osc2Shape: 0.2,
      oscMix: 0.5,
      ringMod: 0,
      attack: 1.2,
      decay: 0.4,
      sustain: 0.85,
      release: 2.0,
      volume: -11,
      drive: 0,
      filterType: "bandpass",
      filterFreq: 1500,
      filterQ: 1.5,
      filterEnvAmount: 0.15,
      filterKeyTrack: 0.5,
      filterAttack: 1.0,
      filterDecay: 0.8,
      filterSustain: 0.6,
      filterRelease: 1.8,
      filterBaseFreq: 800,
      filterOctaves: 2,
      portamento: 0.5,
      portamentoMode: "always",
      lfoRate: 0.8,
      lfoDepth: 0.04,
      lfoType: "sine",
      lfoOsc1Amount: 0.04,
      lfoOsc2Amount: 0,
      lfoFilterAmount: 0.08,
      lfoAmpAmount: 0.12,
      delayTime: 0,
      delayFeedback: 0,
      delayWet: 0,
      reverbDecay: 3.8,
      reverbWet: 0.7,
      reverbSize: 0.9,
      reverbStereo: 0.85,
      reverbDamping: 0.25,
    },
  },

  // ========== PERCUSSION ==========
  {
    name: "Hi-Hat",
    category: "percussion",
    settings: {
      osc1Type: "square",
      osc1Octave: 2,
      osc1Semitone: 0,
      osc1Detune: 0,
      osc1Shape: 0.8,
      osc2Type: "square",
      osc2Octave: 2,
      osc2Semitone: 7,
      osc2Detune: 15,
      osc2Shape: 0.9,
      oscMix: 0.5,
      ringMod: 0.3,
      attack: 0.001,
      decay: 0.05,
      sustain: 0,
      release: 0.05,
      volume: -12,
      drive: 0.4,
      filterType: "highpass",
      filterFreq: 5000,
      filterQ: 1.5,
      filterEnvAmount: 0,
      filterKeyTrack: 0,
      filterAttack: 0.001,
      filterDecay: 0.03,
      filterSustain: 0,
      filterRelease: 0.03,
      filterBaseFreq: 8000,
      filterOctaves: 1,
      portamento: 0,
      portamentoMode: "off",
      lfoRate: 0,
      lfoDepth: 0,
      lfoType: "sine",
      lfoOsc1Amount: 0,
      lfoOsc2Amount: 0,
      lfoFilterAmount: 0,
      lfoAmpAmount: 0,
      delayTime: 0,
      delayFeedback: 0,
      delayWet: 0,
      reverbDecay: 0.5,
      reverbWet: 0.1,
      reverbSize: 0.3,
      reverbStereo: 0.8,
      reverbDamping: 0.9,
    },
  },

  {
    name: "Toms",
    category: "percussion",
    settings: {
      osc1Type: "sine",
      osc1Octave: 0,
      osc1Semitone: 0,
      osc1Detune: 0,
      osc1Shape: 0,
      osc2Type: "triangle",
      osc2Octave: -1,
      osc2Semitone: 0,
      osc2Detune: -2,
      osc2Shape: 0,
      oscMix: 0.4,
      ringMod: 0,
      attack: 0.005,
      decay: 0.3,
      sustain: 0.1,
      release: 0.4,
      volume: -6,
      drive: 0.1,
      filterType: "lowpass",
      filterFreq: 800,
      filterQ: 2.0,
      filterEnvAmount: 0.9,
      filterKeyTrack: 0.8,
      filterAttack: 0.001,
      filterDecay: 0.15,
      filterSustain: 0,
      filterRelease: 0.2,
      filterBaseFreq: 1200,
      filterOctaves: 3,
      portamento: 0,
      portamentoMode: "off",
      lfoRate: 40,
      lfoDepth: 0.15,
      lfoType: "sine",
      lfoOsc1Amount: 0.3,
      lfoOsc2Amount: 0,
      lfoFilterAmount: 0,
      lfoAmpAmount: 0,
      delayTime: 0,
      delayFeedback: 0,
      delayWet: 0,
      reverbDecay: 1.2,
      reverbWet: 0.25,
      reverbSize: 0.5,
      reverbStereo: 0.4,
      reverbDamping: 0.6,
    },
  },

  {
    name: "Kick Drum",
    category: "percussion",
    settings: {
      osc1Type: "sine",
      osc1Octave: -2,
      osc1Semitone: 0,
      osc1Detune: 0,
      osc1Shape: 0,
      osc2Type: "triangle",
      osc2Octave: -2,
      osc2Semitone: 0,
      osc2Detune: 0,
      osc2Shape: 0,
      oscMix: 0.3,
      ringMod: 0,
      attack: 0.001,
      decay: 0.15,
      sustain: 0,
      release: 0.2,
      volume: 0,
      drive: 0.35,
      filterType: "lowpass",
      filterFreq: 200,
      filterQ: 1.0,
      filterEnvAmount: 1.0,
      filterKeyTrack: 0.5,
      filterAttack: 0.001,
      filterDecay: 0.08,
      filterSustain: 0,
      filterRelease: 0.1,
      filterBaseFreq: 800,
      filterOctaves: 4,
      portamento: 0,
      portamentoMode: "off",
      lfoRate: 50,
      lfoDepth: 0.2,
      lfoType: "sine",
      lfoOsc1Amount: 0.5,
      lfoOsc2Amount: 0,
      lfoFilterAmount: 0,
      lfoAmpAmount: 0,
      delayTime: 0,
      delayFeedback: 0,
      delayWet: 0,
      reverbDecay: 0.3,
      reverbWet: 0.05,
      reverbSize: 0.2,
      reverbStereo: 0.1,
      reverbDamping: 0.9,
    },
  },

  {
    name: "Snare",
    category: "percussion",
    settings: {
      osc1Type: "triangle",
      osc1Octave: 1,
      osc1Semitone: 0,
      osc1Detune: 0,
      osc1Shape: 0,
      osc2Type: "square",
      osc2Octave: 2,
      osc2Semitone: 5,
      osc2Detune: 20,
      osc2Shape: 0.7,
      oscMix: 0.6,
      ringMod: 0.4,
      attack: 0.001,
      decay: 0.12,
      sustain: 0.05,
      release: 0.15,
      volume: -8,
      drive: 0.3,
      filterType: "bandpass",
      filterFreq: 2500,
      filterQ: 2.5,
      filterEnvAmount: 0.5,
      filterKeyTrack: 0.3,
      filterAttack: 0.001,
      filterDecay: 0.08,
      filterSustain: 0.1,
      filterRelease: 0.1,
      filterBaseFreq: 1500,
      filterOctaves: 2,
      portamento: 0,
      portamentoMode: "off",
      lfoRate: 0,
      lfoDepth: 0,
      lfoType: "sine",
      lfoOsc1Amount: 0,
      lfoOsc2Amount: 0,
      lfoFilterAmount: 0,
      lfoAmpAmount: 0,
      delayTime: 0,
      delayFeedback: 0,
      delayWet: 0,
      reverbDecay: 0.8,
      reverbWet: 0.15,
      reverbSize: 0.4,
      reverbStereo: 0.5,
      reverbDamping: 0.7,
    },
  },

  // ========== BRASS ==========
  {
    name: "Brass Section",
    category: "brass",
    settings: {
      osc1Type: "sawtooth",
      osc1Octave: 0,
      osc1Semitone: 0,
      osc1Detune: -6,
      osc1Shape: 0,
      osc2Type: "sawtooth",
      osc2Octave: 0,
      osc2Semitone: 0,
      osc2Detune: 6,
      osc2Shape: 0,
      oscMix: 0.5,
      ringMod: 0,
      attack: 0.08,
      decay: 0.15,
      sustain: 0.75,
      release: 0.2,
      volume: -7,
      drive: 0.2,
      filterType: "lowpass",
      filterFreq: 2200,
      filterQ: 1.8,
      filterEnvAmount: 0.5,
      filterKeyTrack: 0.7,
      filterAttack: 0.05,
      filterDecay: 0.1,
      filterSustain: 0.6,
      filterRelease: 0.15,
      filterBaseFreq: 800,
      filterOctaves: 3,
      portamento: 0.03,
      portamentoMode: "legato",
      lfoRate: 5.5,
      lfoDepth: 0.04,
      lfoType: "sine",
      lfoOsc1Amount: 0.04,
      lfoOsc2Amount: 0,
      lfoFilterAmount: 0.08,
      lfoAmpAmount: 0.06,
      delayTime: 0,
      delayFeedback: 0,
      delayWet: 0,
      reverbDecay: 1.8,
      reverbWet: 0.2,
      reverbSize: 0.6,
      reverbStereo: 0.5,
      reverbDamping: 0.5,
    },
  },

  // ========== PLUCK ==========
  {
    name: "Pluck",
    category: "pluck",
    settings: {
      osc1Type: "triangle",
      osc1Octave: 0,
      osc1Semitone: 0,
      osc1Detune: 0,
      osc1Shape: 0,
      osc2Type: "square",
      osc2Octave: 1,
      osc2Semitone: 0,
      osc2Detune: 5,
      osc2Shape: 0.6,
      oscMix: 0.3,
      ringMod: 0,
      attack: 0.001,
      decay: 0.25,
      sustain: 0,
      release: 0.3,
      volume: -8,
      drive: 0.1,
      filterType: "lowpass",
      filterFreq: 3000,
      filterQ: 2.0,
      filterEnvAmount: 0.8,
      filterKeyTrack: 0.9,
      filterAttack: 0.001,
      filterDecay: 0.2,
      filterSustain: 0,
      filterRelease: 0.25,
      filterBaseFreq: 1000,
      filterOctaves: 4,
      portamento: 0,
      portamentoMode: "off",
      lfoRate: 0,
      lfoDepth: 0,
      lfoType: "sine",
      lfoOsc1Amount: 0,
      lfoOsc2Amount: 0,
      lfoFilterAmount: 0,
      lfoAmpAmount: 0,
      delayTime: 0.2,
      delayFeedback: 0.2,
      delayWet: 0.15,
      reverbDecay: 1.2,
      reverbWet: 0.25,
      reverbSize: 0.5,
      reverbStereo: 0.6,
      reverbDamping: 0.5,
    },
  },

  {
    name: "Bell",
    category: "pluck",
    settings: {
      osc1Type: "sine",
      osc1Octave: 0,
      osc1Semitone: 0,
      osc1Detune: 0,
      osc1Shape: 0,
      osc2Type: "sine",
      osc2Octave: 2,
      osc2Semitone: 7,
      osc2Detune: 0,
      osc2Shape: 0,
      oscMix: 0.6,
      ringMod: 0.3,
      attack: 0.001,
      decay: 1.5,
      sustain: 0.2,
      release: 2.0,
      volume: -10,
      drive: 0,
      filterType: "lowpass",
      filterFreq: 4500,
      filterQ: 1.0,
      filterEnvAmount: 0.4,
      filterKeyTrack: 0.8,
      filterAttack: 0.001,
      filterDecay: 1.0,
      filterSustain: 0.3,
      filterRelease: 1.5,
      filterBaseFreq: 2000,
      filterOctaves: 3,
      portamento: 0,
      portamentoMode: "off",
      lfoRate: 0,
      lfoDepth: 0,
      lfoType: "sine",
      lfoOsc1Amount: 0,
      lfoOsc2Amount: 0,
      lfoFilterAmount: 0,
      lfoAmpAmount: 0,
      delayTime: 0,
      delayFeedback: 0,
      delayWet: 0,
      reverbDecay: 3.0,
      reverbWet: 0.4,
      reverbSize: 0.8,
      reverbStereo: 0.7,
      reverbDamping: 0.3,
    },
  },

  // ========== FX ==========
  {
    name: "Noise Sweep",
    category: "fx",
    settings: {
      osc1Type: "square",
      osc1Octave: 2,
      osc1Semitone: 0,
      osc1Detune: 0,
      osc1Shape: 0.9,
      osc2Type: "square",
      osc2Octave: 2,
      osc2Semitone: 3,
      osc2Detune: 25,
      osc2Shape: 0.9,
      oscMix: 0.5,
      ringMod: 0.7,
      attack: 0.3,
      decay: 0.5,
      sustain: 0.3,
      release: 1.0,
      volume: -14,
      drive: 0.5,
      filterType: "bandpass",
      filterFreq: 500,
      filterQ: 5.0,
      filterEnvAmount: 1.0,
      filterKeyTrack: 0,
      filterAttack: 0.2,
      filterDecay: 0.8,
      filterSustain: 0.2,
      filterRelease: 1.2,
      filterBaseFreq: 200,
      filterOctaves: 7,
      portamento: 0.5,
      portamentoMode: "always",
      lfoRate: 0.2,
      lfoDepth: 0.3,
      lfoType: "triangle",
      lfoOsc1Amount: 0,
      lfoOsc2Amount: 0,
      lfoFilterAmount: 0.3,
      lfoAmpAmount: 0,
      delayTime: 0.375,
      delayFeedback: 0.5,
      delayWet: 0.4,
      reverbDecay: 2.5,
      reverbWet: 0.5,
      reverbSize: 0.8,
      reverbStereo: 0.9,
      reverbDamping: 0.4,
    },
  },

  // ========== AMBIENT / DRONE ==========
  {
    name: "Dark Drone",
    category: "ambient",
    settings: {
      osc1Type: "sawtooth",
      osc1Octave: -1,
      osc1Semitone: 0,
      osc1Detune: -12,
      osc1Shape: 0,
      osc2Type: "sawtooth",
      osc2Octave: -1,
      osc2Semitone: -5,
      osc2Detune: 12,
      osc2Shape: 0,
      oscMix: 0.5,
      ringMod: 0,
      attack: 2.5,
      decay: 1.0,
      sustain: 0.9,
      release: 3.5,
      volume: -14,
      drive: 0.08,
      filterType: "lowpass",
      filterFreq: 400,
      filterQ: 1.5,
      filterEnvAmount: 0.15,
      filterKeyTrack: 0.3,
      filterAttack: 2.0,
      filterDecay: 1.5,
      filterSustain: 0.7,
      filterRelease: 3.0,
      filterBaseFreq: 200,
      filterOctaves: 2,
      portamento: 0.8,
      portamentoMode: "always",
      lfoRate: 0.08,
      lfoDepth: 0.02,
      lfoType: "sine",
      lfoOsc1Amount: 0.02,
      lfoOsc2Amount: 0.03,
      lfoFilterAmount: 0.15,
      lfoAmpAmount: 0.12,
      delayTime: 0.75,
      delayFeedback: 0.6,
      delayWet: 0.35,
      reverbDecay: 4.5,
      reverbWet: 0.7,
      reverbSize: 0.95,
      reverbStereo: 0.9,
      reverbDamping: 0.2,
    },
  },

  {
    name: "Ethereal Pad",
    category: "ambient",
    settings: {
      osc1Type: "triangle",
      osc1Octave: 0,
      osc1Semitone: 0,
      osc1Detune: -15,
      osc1Shape: 0.2,
      osc2Type: "sine",
      osc2Octave: 1,
      osc2Semitone: 7,
      osc2Detune: 15,
      osc2Shape: 0,
      oscMix: 0.6,
      ringMod: 0.05,
      attack: 1.8,
      decay: 1.0,
      sustain: 0.85,
      release: 3.0,
      volume: -12,
      drive: 0,
      filterType: "lowpass",
      filterFreq: 2200,
      filterQ: 0.5,
      filterEnvAmount: 0.2,
      filterKeyTrack: 0.6,
      filterAttack: 1.5,
      filterDecay: 1.2,
      filterSustain: 0.7,
      filterRelease: 2.5,
      filterBaseFreq: 800,
      filterOctaves: 3,
      portamento: 0.6,
      portamentoMode: "always",
      lfoRate: 0.15,
      lfoDepth: 0.04,
      lfoType: "sine",
      lfoOsc1Amount: 0.05,
      lfoOsc2Amount: 0.04,
      lfoFilterAmount: 0.12,
      lfoAmpAmount: 0.15,
      delayTime: 0.5,
      delayFeedback: 0.5,
      delayWet: 0.3,
      reverbDecay: 5.0,
      reverbWet: 0.75,
      reverbSize: 0.98,
      reverbStereo: 0.95,
      reverbDamping: 0.15,
    },
  },

  {
    name: "Resonant Drone",
    category: "ambient",
    settings: {
      osc1Type: "sawtooth",
      osc1Octave: 0,
      osc1Semitone: 0,
      osc1Detune: -8,
      osc1Shape: 0,
      osc2Type: "sawtooth",
      osc2Octave: 0,
      osc2Semitone: 0,
      osc2Detune: 8,
      osc2Shape: 0,
      oscMix: 0.5,
      ringMod: 0,
      attack: 1.5,
      decay: 0.8,
      sustain: 0.9,
      release: 2.5,
      volume: -16,
      drive: 0.1,
      filterType: "bandpass",
      filterFreq: 800,
      filterQ: 8.0,
      filterEnvAmount: 0.3,
      filterKeyTrack: 0.7,
      filterAttack: 1.2,
      filterDecay: 2.0,
      filterSustain: 0.6,
      filterRelease: 2.0,
      filterBaseFreq: 400,
      filterOctaves: 4,
      portamento: 0.7,
      portamentoMode: "always",
      lfoRate: 0.12,
      lfoDepth: 0.05,
      lfoType: "triangle",
      lfoOsc1Amount: 0.03,
      lfoOsc2Amount: 0.03,
      lfoFilterAmount: 0.25,
      lfoAmpAmount: 0.08,
      delayTime: 0.625,
      delayFeedback: 0.55,
      delayWet: 0.4,
      reverbDecay: 4.0,
      reverbWet: 0.65,
      reverbSize: 0.9,
      reverbStereo: 0.85,
      reverbDamping: 0.25,
    },
  },

  {
    name: "Shimmer Pad",
    category: "ambient",
    settings: {
      osc1Type: "triangle",
      osc1Octave: 0,
      osc1Semitone: 0,
      osc1Detune: -10,
      osc1Shape: 0.3,
      osc2Type: "triangle",
      osc2Octave: 2,
      osc2Semitone: 0,
      osc2Detune: 10,
      osc2Shape: 0.3,
      oscMix: 0.45,
      ringMod: 0.15,
      attack: 1.2,
      decay: 0.8,
      sustain: 0.85,
      release: 2.8,
      volume: -13,
      drive: 0,
      filterType: "lowpass",
      filterFreq: 3500,
      filterQ: 0.8,
      filterEnvAmount: 0.25,
      filterKeyTrack: 0.7,
      filterAttack: 1.0,
      filterDecay: 1.0,
      filterSustain: 0.6,
      filterRelease: 2.0,
      filterBaseFreq: 1000,
      filterOctaves: 4,
      portamento: 0.5,
      portamentoMode: "always",
      lfoRate: 0.25,
      lfoDepth: 0.06,
      lfoType: "sine",
      lfoOsc1Amount: 0.06,
      lfoOsc2Amount: 0.08,
      lfoFilterAmount: 0.18,
      lfoAmpAmount: 0.2,
      delayTime: 0.375,
      delayFeedback: 0.45,
      delayWet: 0.35,
      reverbDecay: 4.5,
      reverbWet: 0.8,
      reverbSize: 0.95,
      reverbStereo: 0.95,
      reverbDamping: 0.1,
    },
  },

  {
    name: "Deep Space",
    category: "ambient",
    settings: {
      osc1Type: "sine",
      osc1Octave: -2,
      osc1Semitone: 0,
      osc1Detune: -20,
      osc1Shape: 0,
      osc2Type: "triangle",
      osc2Octave: -1,
      osc2Semitone: 7,
      osc2Detune: 20,
      osc2Shape: 0.1,
      oscMix: 0.55,
      ringMod: 0.08,
      attack: 3.0,
      decay: 1.5,
      sustain: 0.95,
      release: 4.0,
      volume: -15,
      drive: 0.05,
      filterType: "lowpass",
      filterFreq: 600,
      filterQ: 1.2,
      filterEnvAmount: 0.1,
      filterKeyTrack: 0.4,
      filterAttack: 2.5,
      filterDecay: 2.0,
      filterSustain: 0.8,
      filterRelease: 3.5,
      filterBaseFreq: 300,
      filterOctaves: 2.5,
      portamento: 1.0,
      portamentoMode: "always",
      lfoRate: 0.05,
      lfoDepth: 0.03,
      lfoType: "sine",
      lfoOsc1Amount: 0.04,
      lfoOsc2Amount: 0.05,
      lfoFilterAmount: 0.2,
      lfoAmpAmount: 0.18,
      delayTime: 0.85,
      delayFeedback: 0.7,
      delayWet: 0.45,
      reverbDecay: 5.0,
      reverbWet: 0.85,
      reverbSize: 0.98,
      reverbStereo: 0.95,
      reverbDamping: 0.1,
    },
  },

  {
    name: "Glass Pad",
    category: "ambient",
    settings: {
      osc1Type: "sine",
      osc1Octave: 0,
      osc1Semitone: 0,
      osc1Detune: -7,
      osc1Shape: 0,
      osc2Type: "sine",
      osc2Octave: 2,
      osc2Semitone: 5,
      osc2Detune: 7,
      osc2Shape: 0,
      oscMix: 0.5,
      ringMod: 0.25,
      attack: 1.5,
      decay: 1.2,
      sustain: 0.8,
      release: 3.0,
      volume: -14,
      drive: 0,
      filterType: "lowpass",
      filterFreq: 4000,
      filterQ: 1.0,
      filterEnvAmount: 0.3,
      filterKeyTrack: 0.8,
      filterAttack: 1.0,
      filterDecay: 1.5,
      filterSustain: 0.5,
      filterRelease: 2.5,
      filterBaseFreq: 1500,
      filterOctaves: 3.5,
      portamento: 0.4,
      portamentoMode: "always",
      lfoRate: 0.18,
      lfoDepth: 0.04,
      lfoType: "triangle",
      lfoOsc1Amount: 0.05,
      lfoOsc2Amount: 0.06,
      lfoFilterAmount: 0.15,
      lfoAmpAmount: 0.22,
      delayTime: 0.425,
      delayFeedback: 0.4,
      delayWet: 0.3,
      reverbDecay: 4.2,
      reverbWet: 0.75,
      reverbSize: 0.92,
      reverbStereo: 0.9,
      reverbDamping: 0.15,
    },
  },

  {
    name: "Grainy Texture",
    category: "ambient",
    settings: {
      osc1Type: "square",
      osc1Octave: -1,
      osc1Semitone: 0,
      osc1Detune: -25,
      osc1Shape: 0.8,
      osc2Type: "square",
      osc2Octave: -1,
      osc2Semitone: 3,
      osc2Detune: 25,
      osc2Shape: 0.7,
      oscMix: 0.5,
      ringMod: 0.2,
      attack: 2.0,
      decay: 1.0,
      sustain: 0.88,
      release: 3.2,
      volume: -18,
      drive: 0.15,
      filterType: "lowpass",
      filterFreq: 1200,
      filterQ: 2.5,
      filterEnvAmount: 0.2,
      filterKeyTrack: 0.5,
      filterAttack: 1.8,
      filterDecay: 1.5,
      filterSustain: 0.65,
      filterRelease: 2.8,
      filterBaseFreq: 500,
      filterOctaves: 3,
      portamento: 0.65,
      portamentoMode: "always",
      lfoRate: 0.22,
      lfoDepth: 0.07,
      lfoType: "triangle",
      lfoOsc1Amount: 0.07,
      lfoOsc2Amount: 0.06,
      lfoFilterAmount: 0.22,
      lfoAmpAmount: 0.15,
      delayTime: 0.55,
      delayFeedback: 0.58,
      delayWet: 0.38,
      reverbDecay: 3.8,
      reverbWet: 0.68,
      reverbSize: 0.88,
      reverbStereo: 0.88,
      reverbDamping: 0.3,
    },
  },

  {
    name: "Evolving Wash",
    category: "ambient",
    settings: {
      osc1Type: "sawtooth",
      osc1Octave: 0,
      osc1Semitone: 0,
      osc1Detune: -18,
      osc1Shape: 0,
      osc2Type: "triangle",
      osc2Octave: 0,
      osc2Semitone: 12,
      osc2Detune: 18,
      osc2Shape: 0.2,
      oscMix: 0.5,
      ringMod: 0.1,
      attack: 2.2,
      decay: 1.2,
      sustain: 0.92,
      release: 3.5,
      volume: -13,
      drive: 0.06,
      filterType: "lowpass",
      filterFreq: 1800,
      filterQ: 1.8,
      filterEnvAmount: 0.35,
      filterKeyTrack: 0.6,
      filterAttack: 1.8,
      filterDecay: 2.0,
      filterSustain: 0.7,
      filterRelease: 3.0,
      filterBaseFreq: 600,
      filterOctaves: 4,
      portamento: 0.75,
      portamentoMode: "always",
      lfoRate: 0.1,
      lfoDepth: 0.08,
      lfoType: "sine",
      lfoOsc1Amount: 0.08,
      lfoOsc2Amount: 0.09,
      lfoFilterAmount: 0.28,
      lfoAmpAmount: 0.25,
      delayTime: 0.7,
      delayFeedback: 0.65,
      delayWet: 0.42,
      reverbDecay: 4.8,
      reverbWet: 0.78,
      reverbSize: 0.96,
      reverbStereo: 0.92,
      reverbDamping: 0.18,
    },
  },

  // ========== NOISE / TEXTURE ==========
  {
    name: "White Noise",
    category: "noise",
    settings: {
      osc1Type: "square",
      osc1Octave: 3,
      osc1Semitone: 0,
      osc1Detune: -50,
      osc1Shape: 0.95,
      osc2Type: "square",
      osc2Octave: 3,
      osc2Semitone: 1,
      osc2Detune: 50,
      osc2Shape: 0.95,
      oscMix: 0.5,
      ringMod: 0.8,
      attack: 0.001,
      decay: 0.1,
      sustain: 1.0,
      release: 0.05,
      volume: -18,
      drive: 0.3,
      filterType: "highpass",
      filterFreq: 2000,
      filterQ: 0.5,
      filterEnvAmount: 0,
      filterKeyTrack: 0,
      filterAttack: 0.001,
      filterDecay: 0.1,
      filterSustain: 1.0,
      filterRelease: 0.05,
      filterBaseFreq: 2000,
      filterOctaves: 0,
      portamento: 0,
      portamentoMode: "off",
      lfoRate: 0,
      lfoDepth: 0,
      lfoType: "sine",
      lfoOsc1Amount: 0,
      lfoOsc2Amount: 0,
      lfoFilterAmount: 0,
      lfoAmpAmount: 0,
      delayTime: 0,
      delayFeedback: 0,
      delayWet: 0,
      reverbDecay: 0.3,
      reverbWet: 0.05,
      reverbSize: 0.2,
      reverbStereo: 0.5,
      reverbDamping: 0.9,
    },
  },

  {
    name: "Pink Noise",
    category: "noise",
    settings: {
      osc1Type: "square",
      osc1Octave: 2,
      osc1Semitone: 0,
      osc1Detune: -30,
      osc1Shape: 0.9,
      osc2Type: "square",
      osc2Octave: 2,
      osc2Semitone: 2,
      osc2Detune: 30,
      osc2Shape: 0.9,
      oscMix: 0.5,
      ringMod: 0.6,
      attack: 0.001,
      decay: 0.1,
      sustain: 1.0,
      release: 0.05,
      volume: -16,
      drive: 0.25,
      filterType: "lowpass",
      filterFreq: 3000,
      filterQ: 0.7,
      filterEnvAmount: 0,
      filterKeyTrack: 0,
      filterAttack: 0.001,
      filterDecay: 0.1,
      filterSustain: 1.0,
      filterRelease: 0.05,
      filterBaseFreq: 3000,
      filterOctaves: 0,
      portamento: 0,
      portamentoMode: "off",
      lfoRate: 0,
      lfoDepth: 0,
      lfoType: "sine",
      lfoOsc1Amount: 0,
      lfoOsc2Amount: 0,
      lfoFilterAmount: 0,
      lfoAmpAmount: 0,
      delayTime: 0,
      delayFeedback: 0,
      delayWet: 0,
      reverbDecay: 0.5,
      reverbWet: 0.08,
      reverbSize: 0.3,
      reverbStereo: 0.6,
      reverbDamping: 0.8,
    },
  },

  {
    name: "Gritty Texture",
    category: "noise",
    settings: {
      osc1Type: "square",
      osc1Octave: 1,
      osc1Semitone: 0,
      osc1Detune: -40,
      osc1Shape: 0.85,
      osc2Type: "sawtooth",
      osc2Octave: 0,
      osc2Semitone: 7,
      osc2Detune: 40,
      osc2Shape: 0.5,
      oscMix: 0.45,
      ringMod: 0.5,
      attack: 0.05,
      decay: 0.2,
      sustain: 0.7,
      release: 0.3,
      volume: -14,
      drive: 0.45,
      filterType: "bandpass",
      filterFreq: 1500,
      filterQ: 3.5,
      filterEnvAmount: 0.4,
      filterKeyTrack: 0.3,
      filterAttack: 0.02,
      filterDecay: 0.15,
      filterSustain: 0.3,
      filterRelease: 0.2,
      filterBaseFreq: 800,
      filterOctaves: 3,
      portamento: 0,
      portamentoMode: "off",
      lfoRate: 8,
      lfoDepth: 0.2,
      lfoType: "square",
      lfoOsc1Amount: 0.15,
      lfoOsc2Amount: 0.1,
      lfoFilterAmount: 0.3,
      lfoAmpAmount: 0,
      delayTime: 0.15,
      delayFeedback: 0.3,
      delayWet: 0.2,
      reverbDecay: 1.0,
      reverbWet: 0.2,
      reverbSize: 0.4,
      reverbStereo: 0.7,
      reverbDamping: 0.6,
    },
  },

  {
    name: "Noisy Sweep",
    category: "noise",
    settings: {
      osc1Type: "square",
      osc1Octave: 2,
      osc1Semitone: 0,
      osc1Detune: -35,
      osc1Shape: 0.92,
      osc2Type: "square",
      osc2Octave: 2,
      osc2Semitone: 5,
      osc2Detune: 35,
      osc2Shape: 0.88,
      oscMix: 0.5,
      ringMod: 0.7,
      attack: 0.2,
      decay: 0.8,
      sustain: 0.4,
      release: 1.2,
      volume: -16,
      drive: 0.4,
      filterType: "lowpass",
      filterFreq: 400,
      filterQ: 4.0,
      filterEnvAmount: 1.0,
      filterKeyTrack: 0,
      filterAttack: 0.1,
      filterDecay: 1.5,
      filterSustain: 0.2,
      filterRelease: 1.8,
      filterBaseFreq: 200,
      filterOctaves: 6,
      portamento: 0,
      portamentoMode: "off",
      lfoRate: 0.3,
      lfoDepth: 0.15,
      lfoType: "triangle",
      lfoOsc1Amount: 0.1,
      lfoOsc2Amount: 0.12,
      lfoFilterAmount: 0.4,
      lfoAmpAmount: 0,
      delayTime: 0.35,
      delayFeedback: 0.45,
      delayWet: 0.3,
      reverbDecay: 2.0,
      reverbWet: 0.4,
      reverbSize: 0.7,
      reverbStereo: 0.85,
      reverbDamping: 0.5,
    },
  },

  {
    name: "Static Burst",
    category: "noise",
    settings: {
      osc1Type: "square",
      osc1Octave: 3,
      osc1Semitone: 0,
      osc1Detune: -45,
      osc1Shape: 0.97,
      osc2Type: "square",
      osc2Octave: 3,
      osc2Semitone: 3,
      osc2Detune: 45,
      osc2Shape: 0.93,
      oscMix: 0.5,
      ringMod: 0.9,
      attack: 0.001,
      decay: 0.08,
      sustain: 0.2,
      release: 0.15,
      volume: -15,
      drive: 0.5,
      filterType: "highpass",
      filterFreq: 3000,
      filterQ: 2.0,
      filterEnvAmount: 0.3,
      filterKeyTrack: 0,
      filterAttack: 0.001,
      filterDecay: 0.05,
      filterSustain: 0.1,
      filterRelease: 0.1,
      filterBaseFreq: 3500,
      filterOctaves: 2,
      portamento: 0,
      portamentoMode: "off",
      lfoRate: 0,
      lfoDepth: 0,
      lfoType: "sine",
      lfoOsc1Amount: 0,
      lfoOsc2Amount: 0,
      lfoFilterAmount: 0,
      lfoAmpAmount: 0,
      delayTime: 0.1,
      delayFeedback: 0.2,
      delayWet: 0.15,
      reverbDecay: 0.8,
      reverbWet: 0.15,
      reverbSize: 0.35,
      reverbStereo: 0.7,
      reverbDamping: 0.8,
    },
  },

  {
    name: "Crackle",
    category: "noise",
    settings: {
      osc1Type: "square",
      osc1Octave: 2,
      osc1Semitone: 0,
      osc1Detune: -25,
      osc1Shape: 0.88,
      osc2Type: "square",
      osc2Octave: 1,
      osc2Semitone: 4,
      osc2Detune: 25,
      osc2Shape: 0.92,
      oscMix: 0.6,
      ringMod: 0.55,
      attack: 0.001,
      decay: 0.04,
      sustain: 0.15,
      release: 0.08,
      volume: -13,
      drive: 0.55,
      filterType: "bandpass",
      filterFreq: 2500,
      filterQ: 5.0,
      filterEnvAmount: 0.5,
      filterKeyTrack: 0.2,
      filterAttack: 0.001,
      filterDecay: 0.03,
      filterSustain: 0.1,
      filterRelease: 0.05,
      filterBaseFreq: 2000,
      filterOctaves: 2.5,
      portamento: 0,
      portamentoMode: "off",
      lfoRate: 15,
      lfoDepth: 0.25,
      lfoType: "square",
      lfoOsc1Amount: 0.2,
      lfoOsc2Amount: 0.18,
      lfoFilterAmount: 0.35,
      lfoAmpAmount: 0.1,
      delayTime: 0.08,
      delayFeedback: 0.15,
      delayWet: 0.12,
      reverbDecay: 0.6,
      reverbWet: 0.12,
      reverbSize: 0.3,
      reverbStereo: 0.65,
      reverbDamping: 0.75,
    },
  },

  {
    name: "Wind",
    category: "noise",
    settings: {
      osc1Type: "square",
      osc1Octave: 1,
      osc1Semitone: 0,
      osc1Detune: -20,
      osc1Shape: 0.8,
      osc2Type: "square",
      osc2Octave: 1,
      osc2Semitone: 7,
      osc2Detune: 20,
      osc2Shape: 0.85,
      oscMix: 0.5,
      ringMod: 0.4,
      attack: 0.8,
      decay: 0.5,
      sustain: 0.9,
      release: 1.5,
      volume: -17,
      drive: 0.2,
      filterType: "bandpass",
      filterFreq: 1200,
      filterQ: 1.5,
      filterEnvAmount: 0.2,
      filterKeyTrack: 0,
      filterAttack: 0.6,
      filterDecay: 0.8,
      filterSustain: 0.7,
      filterRelease: 1.2,
      filterBaseFreq: 800,
      filterOctaves: 2,
      portamento: 0,
      portamentoMode: "off",
      lfoRate: 0.4,
      lfoDepth: 0.12,
      lfoType: "sine",
      lfoOsc1Amount: 0.1,
      lfoOsc2Amount: 0.12,
      lfoFilterAmount: 0.3,
      lfoAmpAmount: 0.2,
      delayTime: 0,
      delayFeedback: 0,
      delayWet: 0,
      reverbDecay: 1.5,
      reverbWet: 0.3,
      reverbSize: 0.6,
      reverbStereo: 0.8,
      reverbDamping: 0.5,
    },
  },

  {
    name: "Digital Glitch",
    category: "noise",
    settings: {
      osc1Type: "square",
      osc1Octave: 2,
      osc1Semitone: 0,
      osc1Detune: -60,
      osc1Shape: 0.95,
      osc2Type: "square",
      osc2Octave: 3,
      osc2Semitone: 11,
      osc2Detune: 60,
      osc2Shape: 0.9,
      oscMix: 0.55,
      ringMod: 1.0,
      attack: 0.001,
      decay: 0.03,
      sustain: 0.05,
      release: 0.05,
      volume: -14,
      drive: 0.6,
      filterType: "highpass",
      filterFreq: 4000,
      filterQ: 3.0,
      filterEnvAmount: 0.6,
      filterKeyTrack: 0.5,
      filterAttack: 0.001,
      filterDecay: 0.02,
      filterSustain: 0,
      filterRelease: 0.03,
      filterBaseFreq: 3000,
      filterOctaves: 3,
      portamento: 0,
      portamentoMode: "off",
      lfoRate: 25,
      lfoDepth: 0.3,
      lfoType: "square",
      lfoOsc1Amount: 0.25,
      lfoOsc2Amount: 0.3,
      lfoFilterAmount: 0.4,
      lfoAmpAmount: 0.15,
      delayTime: 0.125,
      delayFeedback: 0.35,
      delayWet: 0.25,
      reverbDecay: 0.5,
      reverbWet: 0.1,
      reverbSize: 0.25,
      reverbStereo: 0.75,
      reverbDamping: 0.85,
    },
  },
];

// Preset categories for UI organization
export const PRESET_CATEGORIES = {
  piano: "Piano",
  bass: "Bass",
  lead: "Lead",
  pad: "Pad & Strings",
  percussion: "Percussion",
  brass: "Brass",
  pluck: "Pluck",
  ambient: "Ambient & Drone",
  noise: "Noise & Texture",
  fx: "FX & Sound Design",
};

// Helper functions
export function getPresetsByCategory(category: string): InstrumentPreset[] {
  return INSTRUMENT_PRESETS.filter((p) => p.category === category);
}

export function getPresetByName(name: string): InstrumentPreset | undefined {
  return INSTRUMENT_PRESETS.find((p) => p.name === name);
}

export function getAllPresetNames(): string[] {
  return INSTRUMENT_PRESETS.map((p) => p.name);
}

export function getCategoryList(): string[] {
  return Object.keys(PRESET_CATEGORIES);
}
